# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Yolog
baseurl:        ""
url:            "http://www.yolog.tk/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Yolog
  url:          http://www.yolog.tk/
  email:        iam.choiyos0417@gmail.com  
  github:       choiyos
  #twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/choiyos/choiyos.github.io